# Generated by Django 6.1 on 2026-09-09 20:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, help_text='Shown on CSV exports. Leave blank to use your email.', max_length=80)),
                ('currency', models.CharField(choices=[('GBP', '£ Pound'), ('EUR', '€ Euro'), ('USD', '$ US dollar')], default='GBP', max_length=3)),
                ('date_format', models.CharField(choices=[('uk', '9 Sep 2026'), ('us', 'Sep 9, 2026'), ('iso', '2026-09-09')], default='uk', max_length=8)),
                ('week_start', models.CharField(choices=[('mon', 'Monday'), ('sun', 'Sunday')], default='mon', max_length=3)),
                ('weekly_hour_goal', models.DecimalField(blank=True, decimal_places=1, help_text='Optional weekly hours target. Leave blank for none.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('168'))])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
