# Generated by Django 6.1 on 2026-08-16 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shifts", "0001_initial"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="workplace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shifts",
                to="workspaces.workplace",
            ),
        ),
        migrations.DeleteModel(
            name="Workplace",
        ),
    ]
